### ISSUE TITLE
script has error

### ISSUE THREAD

**Issue by dony71** [DanCech/myq-bridge#3]
when executing python script has error below

root@RetrOrangePi:~/myq-bridge# /usr/bin/python /root/myq-bridge/myq.py
2017-07-07 14:10:35,810 INFO Starting
2017-07-07 14:10:35,833 INFO Getting Doors
Traceback (most recent call last):
  File "/root/myq-bridge/myq.py", line 515, in <module>
    sys.exit(main())
  File "/root/myq-bridge/myq.py", line 502, in main
    myq.get_doors()
  File "/root/myq-bridge/myq.py", line 102, in get_doors
    data = self.get('/api/UserDeviceDetails')
  File "/root/myq-bridge/myq.py", line 161, in get
    token = self.get_token()
  File "/root/myq-bridge/myq.py", line 89, in get_token
    token='null')
  File "/root/myq-bridge/myq.py", line 176, in get
    data = r.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DanCech** [comment]
It looks like myq have changed their API, it's returning:
```
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[10727942452977503064]</body></html>
```
Looks like we'll have to figure out the new API to get it working again.

**Comment by dony71** [comment]
this one is already updated and working fine
https://github.com/Einstein42/myq-garage

**Comment by DanCech** [comment]
@dony71 please try the latest master
